# Generated by Django 2.1 on 2018-08-11 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(default='default.png', upload_to='')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=5)),
                ('last_name', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('sex', models.BooleanField()),
                ('age', models.IntegerField(blank=True)),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormalAttire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_and_physique', models.FloatField()),
                ('poise_and_elegance', models.FloatField()),
                ('confidence', models.FloatField()),
                ('stage_presence', models.FloatField()),
                ('total', models.FloatField(null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormalAttireTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_and_physique', models.FloatField()),
                ('poise_and_elegance', models.FloatField()),
                ('confidence', models.FloatField()),
                ('stage_presence', models.FloatField()),
                ('total', models.FloatField(null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='OldStreetFashionAttire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poise_and_bearing', models.FloatField()),
                ('personality', models.FloatField()),
                ('beauty', models.FloatField()),
                ('performance_and_confidence', models.FloatField()),
                ('total', models.FloatField(null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OldStreetFashionAttireTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poise_and_bearing', models.FloatField()),
                ('personality', models.FloatField()),
                ('beauty', models.FloatField()),
                ('performance_and_confidence', models.FloatField()),
                ('total', models.FloatField(null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='PageantNight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_pageant', models.FloatField()),
                ('pageant_proper', models.FloatField()),
                ('total', models.FloatField()),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='PageantProper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_street_fashion', models.FloatField()),
                ('uniform', models.FloatField()),
                ('formal_attire', models.FloatField()),
                ('total', models.FloatField()),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='PageantResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageant_night', models.FloatField()),
                ('question_and_answer', models.FloatField()),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='PrePageant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_attire', models.FloatField()),
                ('panel_interview', models.FloatField()),
                ('essay', models.FloatField()),
                ('talent', models.FloatField()),
                ('total', models.FloatField(null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrePageantTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_attire', models.FloatField()),
                ('panel_interview', models.FloatField()),
                ('essay', models.FloatField()),
                ('talent', models.FloatField()),
                ('total', models.FloatField(null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAndAnswerTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='UniformAttire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poise_and_bearing', models.FloatField()),
                ('personality', models.FloatField()),
                ('beauty', models.FloatField()),
                ('performance_and_confidence', models.FloatField()),
                ('total', models.FloatField(null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UniformAttireTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poise_and_bearing', models.FloatField()),
                ('personality', models.FloatField()),
                ('beauty', models.FloatField()),
                ('performance_and_confidence', models.FloatField()),
                ('total', models.FloatField(null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
    ]
