# Generated by Django 2.1 on 2018-08-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20180811_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='age',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='middle_initial',
        ),
    ]
