# Generated by Django 2.1 on 2018-08-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_auto_20180812_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('idx', 'sex')},
        ),
    ]
