# Generated by Django 2.1 on 2018-08-13 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_auto_20180813_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageantresult',
            name='total',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
