# Generated by Django 2.1 on 2018-08-13 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_pageantresult_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepageant',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate'),
        ),
        migrations.AlterField(
            model_name='prepageant',
            name='judge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
