# Generated by Django 2.1 on 2018-08-13 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0011_auto_20180813_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepageant',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate'),
        ),
        migrations.AlterField(
            model_name='prepageant',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='formalattire',
            unique_together={('candidate', 'judge')},
        ),
        migrations.AlterUniqueTogether(
            name='oldstreetfashionattire',
            unique_together={('candidate', 'judge')},
        ),
        migrations.AlterUniqueTogether(
            name='prepageant',
            unique_together={('candidate', 'judge')},
        ),
        migrations.AlterUniqueTogether(
            name='questionandanswer',
            unique_together={('candidate', 'judge')},
        ),
        migrations.AlterUniqueTogether(
            name='uniformattire',
            unique_together={('candidate', 'judge')},
        ),
    ]
