# Generated by Django 2.1 on 2018-08-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_auto_20180813_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswer',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.RankSix'),
        ),
    ]
